In [17]:
import cv2 as cv
import numpy as np
import pyautogui

In [18]:
image = cv.imread("C:\\Users\\Gusta\\Documents\\Projetos\\Lost Ark\\Fishing_LA\\imgs\\imagem_exclamacao.jpg")


In [19]:
# for image in images:
#     print("Procurando isca.")
#     try:
#         # res = pyautogui.locate("imagem_isca_crop.jpg", image, confidence=0.7)
#         res = pyautogui.locateOnScreen("imagem_isca_crop.jpg", confidence=0.7)
#         print("Isca encontrada.")
#     except:
#         print("Isca nao encontrada")

In [20]:
print(image)

[[[ 29  28  24]
  [ 25  24  20]
  [ 23  19  14]
  ...
  [119 111  94]
  [113 103  86]
  [107  97  80]]

 [[ 26  25  21]
  [ 25  22  18]
  [ 23  20  15]
  ...
  [123 115  98]
  [115 105  88]
  [109  99  82]]

 [[ 24  21  16]
  [ 24  21  16]
  [ 24  21  16]
  ...
  [120 110  92]
  [112 102  84]
  [112 102  84]]

 ...

 [[ 19   1   0]
  [ 41  13   0]
  [182 133  63]
  ...
  [  8   9   7]
  [  1   2   0]
  [  0   1   0]]

 [[  3   4   8]
  [ 15   7   0]
  [ 59  37   9]
  ...
  [ 23  23  23]
  [ 14  14  14]
  [  5   5   5]]

 [[ 13  22  35]
  [ 30  34  39]
  [ 30  21  12]
  ...
  [ 29  29  29]
  [ 28  28  28]
  [ 24  24  24]]]


In [21]:
# Convert the image to hsv
image_hsv = cv.cvtColor(image, cv.COLOR_BGR2HSV)
h, s, v = cv.split(image_hsv)
                        # [24, 87, 217]
lower_yellow = np.array([14, 75, 207])
upper_yellow = np.array([34, 107, 227])

# Define the mask for the threshold
mask = cv.inRange(image_hsv, lower_yellow, upper_yellow)

# Apply the mask using the and operation
yellow_regions = cv.bitwise_and(image_hsv, image_hsv, mask=mask)

# Convert the image back into an rgb image
yellow_regions_rgb = cv.cvtColor(yellow_regions, cv.COLOR_HSV2BGR)

if (yellow_regions != 0).any():
    print("Event logged!")
else:
    print("No event detected")

# cv.imshow("Crop", cropped_image)
cv.imshow("Filtered image", yellow_regions_rgb)
cv.waitKey(0)
cv.destroyAllWindows()


Event logged!


In [22]:
# hsv_image = cv.cvtColor(image, cv.COLOR_BGR2HSV)

# # Display the HSV image
# cv.imshow('HSV Image', hsv_image)
# cv.waitKey(0)
# cv.destroyAllWindows()